-- =============================================================================
-- Migration: 20260519000011_create_leads
-- Purpose:   Customer rental requests — the heart of the platform.
--
-- Constraints enforced at the DB level:
--   - customer_phone must be in normalized form +9665XXXXXXXX
--   - return_date >= pickup_date
--   - rental_days >= 1
--   - consent_accepted must be TRUE
--
-- lead_number is auto-generated by a trigger (see functions_and_triggers
-- migration) in the format SCR-YYYYMM-00001. The trigger is collision-safe
-- via pg_advisory_xact_lock.
-- =============================================================================

create table public.leads (
  id                       uuid primary key default gen_random_uuid(),
  lead_number              text unique,

  customer_name            text null,
  customer_phone           text not null,

  city_id                  uuid not null references public.cities(id)         on delete restrict,
  airport_id               uuid null     references public.airports(id)       on delete set null,
  pickup_location          text null,

  pickup_date              date not null,
  return_date              date not null,
  rental_days              int  not null,

  category_id              uuid null references public.car_categories(id) on delete set null,
  selected_car_id          uuid null references public.cars(id)           on delete set null,
  selected_company_id      uuid null references public.companies(id)      on delete set null,
  selected_offer_id        uuid null references public.offers(id)         on delete set null,

  request_type             public.request_type not null,

  source_page              text null,
  utm_source               text null,
  utm_medium               text null,
  utm_campaign             text null,
  utm_content              text null,
  utm_term                 text null,

  lead_intent_score        public.lead_intent_score null,
  status                   public.lead_status not null default 'new',

  assigned_company_id      uuid null references public.companies(id) on delete set null,
  assigned_branch_id       uuid null references public.branches(id)  on delete set null,
  assigned_whatsapp        text null,

  admin_notes              text null,

  -- Consent — persisted on the lead record for legal defensibility.
  consent_accepted         boolean     not null,
  consent_text_version     text        not null,
  consent_accepted_at      timestamptz not null default now(),
  consent_ip               inet null,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),

  constraint leads_customer_phone_format
    check (customer_phone ~ '^\+9665\d{8}$'),

  constraint leads_assigned_whatsapp_format
    check (assigned_whatsapp is null or assigned_whatsapp ~ '^\+9665\d{8}$'),

  constraint leads_return_after_pickup
    check (return_date >= pickup_date),

  constraint leads_rental_days_positive
    check (rental_days >= 1),

  constraint leads_consent_must_be_true
    check (consent_accepted = true),

  constraint leads_lead_number_format
    check (lead_number is null or lead_number ~ '^SCR-\d{6}-\d{5}$')
);

comment on table public.leads is
  'Customer rental requests. Every lead must have consent_accepted = true. Customer data is never exposed publicly.';

comment on column public.leads.customer_phone is
  'Normalized Saudi phone: +9665XXXXXXXX. Normalization happens in the application layer before insert.';

comment on column public.leads.lead_number is
  'Human-friendly identifier in the format SCR-YYYYMM-NNNNN. Auto-generated by trigger; never set directly by application.';

comment on column public.leads.rental_days is
  'Computed by the application before insert as (return_date - pickup_date). DB enforces rental_days >= 1.';

comment on column public.leads.consent_text_version is
  'Version identifier of the consent text the customer accepted (e.g. ''v1-2026-05''). Allows audit when the consent text changes.';
